### ISSUE TITLE
Calling `BrownianTree` with `t > t1` returns `None`

### ISSUE THREAD

**Issue by patrick-kidger** [google-research/torchsde#10]
Repro:
```
torchsde.BrownianTree(t0=torch.tensor(0.), w0=torch.tensor(0.))(2.)
```
Not helped by the implicit assumption that `t1 = t0 + 1`.

**Comment by lxuechen** [comment]
This seems to be an issue caused by `t` > `t1` + `safety`, where `safety` is one of the arguments for initialization. I agree that the user shouldn't be obliged to always set the safety factor precisely. 

Will send in a fix shortly.

**Comment by patrick-kidger** [comment]
CLosing as resolvedi n #28, as querying with t > t1 is no longer possible.
