### ISSUE TITLE
Experiments Code in "Neural SDEs AS Infinite-Dimensional GANs"

### ISSUE THREAD

**Issue by pmcsh04** [google-research/torchsde#110]
Could you please provide the reproducible experimental source code for experiment 4.2-4.4?
Or, I would like to see the code for the reproducible metric (Classification, Prediction, MMD) to check the results of running the experiment.

thanks for reading.

**Comment by patrick-kidger** [comment]
Hi! I've seen your email I just need to get around to responding. 😅 I'll send you something later today.
