### ISSUE TITLE
how to perform the sde with decreasing time

### ISSUE THREAD

**Issue by Jarvisarmy** [google-research/torchsde#115]
When I run the default sdeint, it says "evaluation times 'ts' must be strictly increasing", is there any setting or solver that can be used to solve the problem with decreasing time.

**Comment by Jarvisarmy** [comment]
I figure out I can pass in the increasing time, and modify the time in f and g.

**Comment by lxuechen** [comment]
Exactly, say you'd like to solve from t1 backwards to t0, where t1 > t0. 

You could solve another SDE from -t1 to -t0, where the new f and g functions internally negates the time.
