### ISSUE TITLE
Query on KL_Scheduler

### ISSUE THREAD

**Issue by PANG-98** [google-research/torchsde#118]
Hey fellows, excellent work and really appreciate the released code. But, I'm a little bit confused about the "kl_scheduler" used in "latent_sde_lorenz.py". What does it mean, and do I really need it ?

**Comment by lxuechen** [comment]
Part of this is due legacy code that we wanted to support still. It's not strictly necessary. 

The point of this was that you could have a setting where you'd like to weight the penalty incurred by different parts of the KL objective differently. 

Say you solve from t0 to t1 and then to t2. You'd get 2 KL penalties -- one for the part between t0 to t1, and another from t1 to t2. `kl_scheduler ` allows you then to adjust the weight assigned to the two components.
