### ISSUE TITLE
torchsde pypi package is misformated

### ISSUE THREAD

**Issue by vladmandic** [google-research/torchsde#131]
using latest **pip 23.2**:

> pip install torchsde

```log
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7".
pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or
contact the author to suggest that they release a version with a conforming dependency specifiers.
Discussion can be found at https://github.com/pypa/pip/issues/12063
```

**Comment by pradyunsg** [comment]
(you need to drop the `.*`)

**Comment by JacobDPoland** [comment]
I'm getting this error as well. How do you drop the *? Is there a text file to change or a command to type that will do this?

**Comment by eniora** [comment]
> > I'm getting this error as well. How do you drop the *? Is there a text file to change or a command to type that will do this?
> 
> you have to remove the `.*` at line18 `numpy>=1.19.*` in `.\stable-diffusion-webui\venv\Lib\site-packages\torchsde-0.2.5.dist-info\METADATA`

Thank you this worked!

**Comment by MarianKoleff** [comment]
In what file do I have to make this change? (remove the  .* )

**Comment by MarianKoleff** [comment]
I have this exact issue with installation of ComfyUI Impact Pack, but there's no file METADA anywhere in ComfyUI and it's subfolders. Can it be in Miniconda3?

**Comment by eniora** [comment]
> I have this exact issue with installation of ComfyUI Impact Pack, but there's no file METADA anywhere in ComfyUI and it's subfolders. Can it be in Miniconda3?

Editing line 18 in the **METADATA** file in **%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchsde-0.2.5.dist-info** did it for me as explained by @angryptonX

**Comment by Bakobiibizo** [comment]
in case you cant find it also look in
%userprofile%\AppData\Local\Programs\miniconda3\envs\%environmentname%\Lib\site-packages\storchsde-0.25.dist-info
and 
%userprofile%\.conda\envs\%environmentname%\Lib\site-packages\storchsde-0.25.dist-info

**Comment by egoegoegoegoego** [comment]
> > I'm getting this error as well. How do you drop the *? Is there a text file to change or a command to type that will do this?
> 
> you have to remove the `.*` at line18 `numpy>=1.19.*` in `.\stable-diffusion-webui\venv\Lib\site-packages\torchsde-0.2.5.dist-info\METADATA`

hi, i don't have line 18 on my METADATA it only shows this...
Metadata-Version: 2.1
Name: torchsde
Version: 0.2.5
Summary: SDE solvers and stochastic adjoint sensitivity analysis in PyTorch.
Home-page: https://github.com/google-research/torchsde
Author: Xuechen Li
Author-email: lxuechen@cs.toronto.edu
License: UNKNOWN
Platform: UNKNOWN
Classifier: Programming Language :: Python :: 3
Classifier: License :: OSI Approved :: Apache Software License
Requires-Python: ~=3.6
Requires-Dist: boltons (>=20.2.1)
Requires-Dist: torch (>=1.6.0)
Requires-Dist: trampoline (>=0.1.2)
Requires-Dist: numpy (==1.19.*) ; python_version < "3.7"
Requires-Dist: scipy (==1.5.*) ; python_version < "3.7"
Requires-Dist: numpy (>=1.19.*) ; python_version >= "3.7"
Requires-Dist: scipy (>=1.5) ; python_version >= "3.7"

UNKNOWN

**Comment by StupidNut** [comment]
> hi, i don't have line 18 on my METADATA it only shows this...


replace the text in the metadata file with the one below:

Metadata-Version: 2.1
Name: torchsde
Version: 0.2.5
Summary: SDE solvers and stochastic adjoint sensitivity analysis in PyTorch.
Home-page: https://github.com/google-research/torchsde
Author: Xuechen Li
Author-email: [lxuechen@cs.toronto.edu](mailto:lxuechen@cs.toronto.edu)
License: UNKNOWN
Platform: UNKNOWN
Classifier: Programming Language :: Python :: 3
Classifier: License :: OSI Approved :: Apache Software License
Requires-Python: ~=3.6
Requires-Dist: boltons (>=20.2.1)
Requires-Dist: torch (>=1.6.0)
Requires-Dist: trampoline (>=0.1.2)
Requires-Dist: numpy (==1.19.) ; python_version < "3.7"
Requires-Dist: scipy (==1.5.) ; python_version < "3.7"
Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"
Requires-Dist: scipy (>=1.5) ; python_version >= "3.7"

UNKNOWN

**Comment by danteadc** [comment]
> > hi, i don't have line 18 on my METADATA it only shows this...
> 
> you need to fix the second line _Requires-Dist: numpy_ (which, except for the file name, will be the 18th line in order) in the METADATA file **Requires-Dist: numpy (>=1.19.*) ; python_version >= "3.7"**
> 
> on
> 
> Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"

Hello, I did this and it still didn't work. I still get the same message.

"DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063".

Is there any other way around?

**Comment by patrick-kidger** [comment]
Hi -- with #133 this should now be fixed. This will still need another public release (with a new version number_, and the `.github/workflows` needs updating to use modern versions of Python.

We (the authors) intend to leave torchsde in "community maintenace" mode. We'd be happy to merge pull requests fixing things as required, but don't intend to do further work on this library ourselves.

**Comment by johnmora1984** [comment]
> 

I am also experiencing the same issue after doing the suggested edits tot he metadata file. What could I be doing wrong?

**Comment by jphan32** [comment]
This issue has been resolved and merged in PR https://github.com/google-research/torchsde/pull/133.

**Comment by vladmandic** [comment]
What is the plan to publish a new package?

**Comment by patrick-kidger** [comment]
If someone wants to bump the version number (+I think also fix the CI crashing) then I'll be happy to publish a new version.

We (the original authors) have largely moved on. (In my case, to [Diffrax](https://github.com/patrick-kidger/diffrax).) But this has turned out to be a popular package, so we've decided to keep it going in "community maintenance" mode. We won't be working on this library directly ourselves, but will be happy to merge PRs as they are submitted.

**Comment by MojoMoe** [comment]
FYI in Windows 11 I was able to find METADATA in this folder and edited line 18 to remove  .*

C:\Python310\Lib\site-packages\torchsde-0.2.5.dist-info

I installed Python in the root of C:\ so you will have to find where your Python installation is located first. Also I tend not to follow the recommended use of venv, so you might have to find this folder in your venv.

**Comment by Fanghanmo2412** [comment]
I'm facing the same issue, please publish the new version if possible
Many thanks!

**Comment by cosmicnexus44** [comment]
> > I'm getting this error as well. How do you drop the *? Is there a text file to change or a command to type that will do this?
> 
> you have to remove the `.*` at line18 `numpy>=1.19.*` in `.\stable-diffusion-webui\venv\Lib\site-packages\torchsde-0.2.5.dist-info\METADATA`

TY, this worked here for me!

**Comment by patrick-kidger** [comment]
As per above:

> We (the authors) intend to leave torchsde in "community maintenace" mode. We'd be happy to merge pull requests fixing things as required, but don't intend to do further work on this library ourselves.

If someone wants to submit the PR bumping the version number (and I think also fixing CI failures), then we can do a new release.

**Comment by vladmandic** [comment]
@patrick-kidger i'm not sure what do you mean by that - only maintainers can create a release and publish to pypi.
and other than creating a release, i dont see what would "bumping the version number" pr do?

**Comment by patrick-kidger** [comment]
It would perform the necessary step of increasing the version number -- and as a prerequisite, this would also ensure that the CI is up-to-date.
Once that's done then indeed, a maintainer (=me) can push a new version to PyPI.

**Comment by vladmandic** [comment]
but that's just a oneliner? ok, i've created a PR #137

**Comment by asifkhan1308** [comment]
> > I'm getting this error as well. How do you drop the *? Is there a text file to change or a command to type that will do this?
> 
> you have to remove the `.*` at line18 `numpy>=1.19.*` in `.\stable-diffusion-webui\venv\Lib\site-packages\torchsde-0.2.5.dist-info\METADATA`

i tried still it occurs.:
Requires-Dist: numpy (==1.19.*) ; python_version < "3.7"
Requires-Dist: scipy (==1.5.*) ; python_version < "3.7"
Requires-Dist: numpy (>=1.19) ; python_version >= "3.7"
Requires-Dist: scipy (>=1.5) ; python_version >= "3.7"

even with this it occurs the same error again:
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

**Comment by TSulo8** [comment]
Still having an issue with this, on a mac & a total novice on what it even takes to remove .*
How do I start to remove that?

**Comment by STEMBytes** [comment]
please update this version to conform to PiP .. there are a lot of people who are getting this error and need someone to update it.

**Comment by vladmandic** [comment]
closing as resolved.

**Comment by haab1001** [comment]
Update failed.
No module named 'pygit2'
Update succeeded.
[System ARGV] ['entry_with_update.py']
Traceback (most recent call last):
  File "entry_with_update.py", line 45, in <module>
    from launch import *
  File "D:\AI_code\Fooocus\launch.py", line 22, in <module>
    from modules.config import path_checkpoints, path_loras, path_vae_approx, path_fooocus_expansion, \
  File "D:\AI_code\Fooocus\modules\config.py", line 7, in <module>
    import modules.sdxl_styles
  File "D:\AI_code\Fooocus\modules\sdxl_styles.py", line 5, in <module>
    from modules.util import get_files_from_folder
  File "D:\AI_code\Fooocus\modules\util.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy


I fixed the change in METADATA but now i get this error

**Comment by roninDday** [comment]
我的 Mac上 只有torchsde-0.2.6.dist-info，依然遇到这个问题

DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 24.1 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

怎样做才能安装insightface

**Comment by YD-JJ** [comment]
> > 我在安装 ComfyUI Impact Pack 时遇到了这个确切的问题，但是 ComfyUI 及其子文件夹中的任何地方都没有文件 METADA。它可以在 Miniconda3 中吗？
> 
> 我认为这是因为 ComfyUI 没有自己的 venv 文件夹，因此您必须在 appdata 中编辑该文件夹，例如：
> 
> 在 **%userprofile%\AppData\Local\Programs\Python\Python310\Lib\site-packages\torchsde-0.2.5.dist-info** 中编辑 **METADATA** 文件中的第 18 行，如解释的那样为我完成了此操作
> 
> 您的路径可能会有所不同，具体取决于您的 python 版本等。
这个办法真的很有效，如果你使用的是秋叶大佬的comfyui，那么要在comfyui中的python中修改
