### ISSUE TITLE
Performance Improvement Inquiry: Experiencing Slow Execution with TorchSDE

### ISSUE THREAD

**Issue by wyl010607** [google-research/torchsde#141]
Dear Developers,

I hope this message finds you well. I am reaching out to bring to your attention an issue I have been facing while working with TorchSDE, and to seek possible resolutions to optimize its performance.

I have been utilizing TorchSDE to build my NSDE in my project, and have noticed that the execution time is considerably slow. I am wondering if there are any recommended practices or optimizations that can be applied to improve the execution speed of TorchSDE. I am open to exploring different configurations or any other suggestions you might have to address this issue.

Here are some specifics regarding my setup:
- TorchSDE Version: [0.2.6]
- PyTorch Version: [2.0.0]
- Hardware Configuration: [nvidia 4070 with cuda 12.2]

Thank you for your time and consideration. I am looking forward to hearing from you at your earliest convenience.

Warm regards,
yl wang

**Comment by wyl010607** [comment]
Dear Developers,

I have identified the cause of the issue. In the sdeint function, I changed the ts parameter to range(1, 500) while retaining the default value for dt. When I set dt to 1, the execution time improved to an acceptable level. I would like to know if this adjustment is appropriate.

**Comment by patrick-kidger** [comment]
Yes, that's reasonable.

If performance is important to you then you might also like to try [Diffrax](https://github.com/patrick-kidger/diffrax), which is a spiritual successor to torchsde and should be even faster.
