### ISSUE TITLE
[On dev branch] New BrownianInterval hangs when `dt` is very small

### ISSUE THREAD

**Issue by lxuechen** [google-research/torchsde#36]
I think this relates to the issue @patrick-kidger mentioned that when running the scalar diagnostics, large amounts of memory is consumed. I'm seeing this also on my machine. 

I've managed to pinpoint the issue: When `tb-ta` is very small, the dependency tree creation phase hangs, with `_set_points` being repeated indefinitely. More specifically, [this](https://github.com/google-research/torchsde/blob/4c70f3e0207a8a9b27f2a91ccc0b4e8cda3fd431/torchsde/_brownian/brownian_interval.py#L539) line.

**Comment by patrick-kidger** [comment]
How small is small? I've tested this down to `dt=1e-7` (so 100 times smaller than the default `dt_min`) and things seem fine. (It terminates in 80 seconds on my machine.)

**Comment by lxuechen** [comment]
Good point, I'm observing values of `tb - ta` to be as small as `1.7763568394002505e-15`. This is really a result of the while loop in `base_solver.py` still stepping forward despite `curr_t` being set to ts[-1].

This is clearly due to limited floating point precision, though the precise reason I have not figured out yet.

**Comment by patrick-kidger** [comment]
Are you saying there's still a bug in `base_solver.py` somewhere?

This has made me realise, though that we can get an arbitrarily small timestep on the final step. I'll update the heuristics for creating the dependency tree to be a bit smarter.

**Comment by lxuechen** [comment]
That is clearly the case, i.e. curr_t = ts[-1] < out_t=ts[-1].

**Comment by patrick-kidger** [comment]
Can you provide a repro? Just eyeballing the integration code nothing really looks wrong to me.

**Comment by lxuechen** [comment]
> Can you provide a repro? Just eyeballing the integration code nothing really looks wrong to me.

Try running `python -m diagnostics.ito_scalar` on branch `dev-remove-tuple`. The problem occurs regardless of which random seed I use on my machine. 

I think ultimately, we should step pass the boundary and pull back later on.

**Comment by patrick-kidger** [comment]
Right, figured it out - this was a bug in BInterval, not in the solver. I'll have a PR in a few moments.
