### ISSUE TITLE
Install command fails if SSH key not set

### ISSUE THREAD

**Issue by patrick-kidger** [google-research/torchsde#5]
```
pip install git+ssh://git@github.com/google-research/torchsde
```
throws an error for me (`git@github.com: Permission denied (publickey)`), presumably because one is required to have set their [SSH key with GitHub](https://docs.github.com/en/github/authenticating-to-github/error-permission-denied-publickey).

Is there a particular reason for this choice? Rather than the usual
```
pip install git+https://github.com/google-research/torchsde.git
```
which is a little more user-friendly. :)

**Comment by lxuechen** [comment]
Thanks for pointing this out! I'll send in a fix soon.
