### ISSUE TITLE
Build Fails 

### ISSUE THREAD

**Issue by ucalyptus** [google-research/torchsde#53]
# Reproduce
https://colab.research.google.com/gist/ucalyptus/39977d8f157270a330ef04fc0c9707a9/test-torchsde.ipynb

**Comment by patrick-kidger** [comment]
Well, try doing what it says and installing torch ;)

That said, it's true we should a PEP518 `pyproject.toml` so that that happens automatically.

**Comment by ucalyptus** [comment]
@patrick-kidger definitely works when torch is pre installed (eg on Colab), but I'm not able to use torchsde in setuptools
as `import torch` comes up .
An example of what we are doing https://github.com/DiffEqML/torchdyn/blob/master/setup.cfg

**Comment by patrick-kidger** [comment]
Resolved with #56
