### ISSUE TITLE
sdeint_adjoint doesn't seem to work on GPU

### ISSUE THREAD

**Issue by roberto1648** [google-research/torchsde#62]
Run the code in latent_sde.py. On cpu everything works fine, but when switching to GPU and using sdeint_adjoint() the following error appears:

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

As mentioned above, the only difference is the use of a GPU. Tried, just in case, moving leaf variables to device and it didn't fix the problem (they had already been moved to the appropriate device in the original code). I can also confirm that all variables have requires_grad = True.

Finally, sdeint() works on both CPU and GPU.

**Comment by lxuechen** [comment]
Thanks for the report! Could you provide the version of pytorch you're running with and the branch of torchsde you're checking out?

**Comment by roberto1648** [comment]
Sorry it must be the version! checked and mine is 1.3.1 (also using the master branch).
Thanks for your response and congratulations on the awesome work.

**Comment by lxuechen** [comment]
Sorry that we weren't absolutely clear on this. `setup.py` has the versions of various packages annotated, but we never stated the requirements in the README files. We will make sure we do so for the next release.

**Comment by roberto1648** [comment]
Thank you that would be nice. Looking forward to see what you guys come up with next.

In case others try to run torchsde from an existing conda env, as of today (2020-09-24) updating torch from conda (i.e., conda update pytorch torchvision) will only bring it up to 1.4, you have to do: 

conda install pytorch torchvision cudatoolkit=10.2 -c pytorch 

to get it to 1.6 (the latest stable version as of today and the requirement for torchsde).
