### ISSUE TITLE
Examples for paper's toy problems

### ISSUE THREAD

**Issue by MiguelFreire** [google-research/torchsde#83]
Hey,

Could you guys share the example code for the toy problems presented in the paper? Especially the one for Stochastic Lorenz Attractor? 

I was looking at how to solve a system of stochastic differential equations using torchsde where there is inter-dependecy between some of the functions. Can you help me out?

Cheers,
Miguel

**Comment by dnguyengithub** [comment]
Hello, 

First of all, thank you for the code.
Could you please share the script/notebook for the Stochastic Lorenz system?

Thank you in advance!
Duong

**Comment by lxuechen** [comment]
It's [here](https://github.com/google-research/torchsde/blob/master/examples/latent_sde_lorenz.py)

**Comment by MiguelFreire** [comment]
Thank you! Cheers!
