### ISSUE TITLE
Global entropy doesn't determine sampled values outside of [t0, t1] for `BrownianTree`

### ISSUE THREAD

**Issue by lxuechen** [google-research/torchsde#9]
Following the [note](https://github.com/google-research/torchsde/pull/7#issuecomment-671078247), the `entropy` argument passed to initialize `BrownianTree` doesn't govern the random numbers sampled outside the predetermined range [t0, t1]. 

Queries of this type is rate. Though, at the very least, there should be some warning or documentation on this.

**Comment by patrick-kidger** [comment]
Closing as resolved in #28, as querying outside [t0, t1] is no longer possible.
