### ISSUE TITLE
Upload to PyPI

### ISSUE THREAD

**Issue by patrick-kidger** [google-research/torchsde#96]
It'd be nice to make torchsde available on PyPI. There's a few limitations with hosting it only on GitHub, most notably that (a) you can't specify a range of acceptable versions (`torchsde>=0.2.4`), and (b) it's not possible to upload any _other_ package to PyPI that depends on torchsde: PyPI disallows uploading packages that have dependencies outside of PyPI.

**Comment by lxuechen** [comment]
Good call! Let's do this after neurips.

**Comment by dhirschfeld** [comment]
FYI: `torchsde` is available via `conda-forgge`:
```
conda install -c conda-forge torchsde
```
https://github.com/conda-forge/torchsde-feedstock

**Comment by SauravMaheshkar** [comment]
@patrick-kidger Request for this issue to be closed as the package already is available on PyPI, for reference visit [**this page**](https://pypi.org/project/torchsde/).

**Comment by patrick-kidger** [comment]
Ah yep!
